# Grafana Loki datasource provisioning for ECS deployment
# Auto-configures Loki datasource for log querying
#
# Loki is accessed via Service Connect DNS name 'loki' on port 3100
# No authentication required (internal service)
#
# Requirements: 4.1, 4.2, 4.3

apiVersion: 1

datasources:
  # Loki datasource for log aggregation
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      # Maximum number of log lines to return per query
      maxLines: 1000
      # Timeout for queries (in seconds)
      timeout: 60
